### ISSUE TITLE
Poor debugging options

### ISSUE THREAD

**Issue by mjallday** [Vantiv/litle-sdk-for-python#2]
I'm in the middle of debugging some timeout issues with Litle and it's very difficult to find out what's happening inside this library without dropping into a debugger and stepping through the code. 

Ideally this library should log to a debugger and then I could configure the logger via the normal methods.

**Comment by brianarnold789** [comment]
[vantiv-sdk-for-python](https://github.com/Vantiv/vantiv-sdk-for-python) is preferred, closing issue
