### ISSUE TITLE
MasterCard New BIN range 222100-272099 support

### ISSUE THREAD

**Issue by wraziens** [Vantiv/litle-sdk-for-python#7]
Can we get test cards for this SDK to test the new MasterCard Bin ranges in the Sandbox option?

**Comment by brianarnold789** [comment]
@wraziens,
The Sandbox does not use account ranges, it is strictly a stateless simulator. The responses are derived mainly from the card number. More info on Sandbox features can be found here: http://litleco.github.io/sandbox/

**Comment by wraziens** [comment]
Thanks for the info @brianarnold789. Do you have an example of a 2-bin card number that would be approved in the sanbox?

**Comment by brianarnold789** [comment]
@wraziens,
Any card in the range that ends in '000' will elicit an 'Approved' response from the Sandbox. ex.: 2221000000000000
